# This option should only be used if an issue occurs.
# SirBlobman may ask you to enable it if you ask for help.
#
# Default: false
debug-mode: false

# Should FallAvert ignore players that have access to flight?
#
# Default: true
allow-flying: true

commands:
  # Which commands should not work while flying?
  # DO NOT forget the `/` in front of the commands.
  # You can add "*" to the list to block ALL commands.
  blocked-command-list:
    - "/tp"
    - "/tpa"
    - "/fly"
    - "/warp"
    - "/island"

  # Which commands are allowed during combat?
  # This list is used if you want to un-block a command that is blocked by the other list.
  # You can add "*" to the list to allow ALL commands.
  #
  # Extra Information: This list overrides the blocked command list
  allowed-command-list:
    - "/tpo"

punishments:
  # Set this to true if players should be punished for logging out in the air.
  #
  # Default: false
  enabled: false

  # A list of commands to be executed as punishments
  # These commands will be executed by console
  #
  # Placeholders:
  # - {player}: The username of the player that logged out
  #
  # Default:
  # - "kill {player}"
  commands:
  - "kill {player}"

messages:
  blocked-command: "&c&oYou cannot do &a{command}&c&o while falling!"
  reload: "&aSuccessfully reloaded config.yml for FallAvert."
  not-player: "&cYou are not a Player!"
  invalid-target: "&cInvalid target!"
